PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS habnews_runtime_state(key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT OR IGNORE INTO habnews_runtime_state VALUES('enabled','false');
INSERT OR IGNORE INTO habnews_runtime_state VALUES('llm_state','auth_required');
CREATE TABLE IF NOT EXISTS habnews_source(id TEXT PRIMARY KEY, baseline INTEGER DEFAULT 0, last_poll REAL, last_success REAL, etag TEXT, modified TEXT, failures INTEGER DEFAULT 0, next_poll REAL DEFAULT 0, health TEXT DEFAULT 'unverified');
CREATE TABLE IF NOT EXISTS habnews_observation(id TEXT PRIMARY KEY, source_id TEXT NOT NULL, provider_id TEXT NOT NULL,url TEXT NOT NULL,digest TEXT NOT NULL, metadata TEXT NOT NULL,first_seen REAL NOT NULL,stage TEXT NOT NULL,UNIQUE(source_id,provider_id,digest));
CREATE TABLE IF NOT EXISTS habnews_event(id TEXT PRIMARY KEY,identity TEXT UNIQUE NOT NULL,version INTEGER NOT NULL,status TEXT NOT NULL,priority TEXT NOT NULL,first_seen REAL NOT NULL,updated REAL NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_event_version(event_id TEXT NOT NULL,version INTEGER NOT NULL,digest TEXT NOT NULL,payload TEXT NOT NULL,created REAL NOT NULL,PRIMARY KEY(event_id,version),FOREIGN KEY(event_id) REFERENCES habnews_event(id));
CREATE TABLE IF NOT EXISTS habnews_event_observation(event_id TEXT NOT NULL,observation_id TEXT UNIQUE NOT NULL,PRIMARY KEY(event_id,observation_id));
CREATE TABLE IF NOT EXISTS habnews_evidence(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,event_version INTEGER NOT NULL,source_id TEXT NOT NULL,family TEXT NOT NULL,primary_source INTEGER NOT NULL,url TEXT NOT NULL,passage TEXT NOT NULL,digest TEXT NOT NULL,retrieved REAL NOT NULL,tombstone INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS habnews_fact(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,payload TEXT NOT NULL,evidence_ref TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_image_candidate(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,version INTEGER NOT NULL,payload TEXT NOT NULL,rights TEXT NOT NULL,created REAL NOT NULL,path TEXT,tombstone INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS habnews_draft(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,event_version INTEGER NOT NULL,version INTEGER NOT NULL,image_version INTEGER NOT NULL,hash TEXT NOT NULL,body TEXT NOT NULL,metadata TEXT NOT NULL,status TEXT NOT NULL,created REAL NOT NULL,UNIQUE(event_id,event_version,version));
CREATE TABLE IF NOT EXISTS habnews_decision(id TEXT PRIMARY KEY,draft_id TEXT NOT NULL,hash TEXT NOT NULL,user_id INTEGER NOT NULL,action TEXT NOT NULL,media_status TEXT NOT NULL,created REAL NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_queue(id TEXT PRIMARY KEY,kind TEXT NOT NULL,identity TEXT UNIQUE NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER DEFAULT 0,next_at REAL NOT NULL,lease TEXT,lease_until REAL,created REAL NOT NULL);
CREATE INDEX IF NOT EXISTS habnews_queue_due ON habnews_queue(kind,status,next_at);
CREATE TABLE IF NOT EXISTS habnews_outbox(id TEXT PRIMARY KEY,draft_id TEXT,recipient INTEGER NOT NULL,part INTEGER NOT NULL,method TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',next_at REAL NOT NULL,lease TEXT,lease_until REAL,message_id INTEGER,created REAL NOT NULL,UNIQUE(draft_id,recipient,part));
CREATE INDEX IF NOT EXISTS habnews_outbox_due ON habnews_outbox(status,next_at);
CREATE TABLE IF NOT EXISTS habnews_attempt(id TEXT PRIMARY KEY,outbox_id TEXT NOT NULL,status TEXT NOT NULL,created REAL NOT NULL,message_id INTEGER);
CREATE TABLE IF NOT EXISTS habnews_callback(nonce TEXT PRIMARY KEY,draft_id TEXT NOT NULL,action TEXT NOT NULL,recipient INTEGER NOT NULL,message_id INTEGER,hash TEXT NOT NULL,used INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS habnews_update(id TEXT PRIMARY KEY,created REAL NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_feed_callback(nonce TEXT PRIMARY KEY,observation_id TEXT NOT NULL,recipient INTEGER NOT NULL,message_id INTEGER,digest TEXT NOT NULL,used INTEGER DEFAULT 0,outbox_id TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_revision(message_id INTEGER PRIMARY KEY,event_id TEXT NOT NULL,draft_id TEXT NOT NULL,recipient INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_budget(id TEXT PRIMARY KEY,day TEXT NOT NULL,event_id TEXT NOT NULL,kind TEXT NOT NULL,reserved INTEGER NOT NULL,actual INTEGER,status TEXT NOT NULL,metadata TEXT NOT NULL,created REAL NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,created REAL NOT NULL,kind TEXT NOT NULL,subject TEXT NOT NULL,metadata TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS habnews_incident(id TEXT PRIMARY KEY,status TEXT NOT NULL,reason TEXT NOT NULL,created REAL NOT NULL,recovered REAL);
CREATE TRIGGER IF NOT EXISTS habnews_audit_no_update BEFORE UPDATE ON habnews_audit BEGIN SELECT RAISE(ABORT,'append-only audit'); END;
